language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lgmartins96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lgmartins96/react-test npm test

after_sucess:
  - docker build -t lgmartins96/multi-client ./client
  - docker build -t lgmartins96/multi-server ./server
  - docker build -t lgmartins96/multi-worker ./worker
  - docker build -t lgmartins96/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lgmartins96/multi-client
  - docker push lgmartins96/multi-server
  - docker push lgmartins96/multi-worker
  - docker push lgmartins96/multi-nginx